version: '3.6'

services:
  provider-api-mock-service:
    build: ../datahog
    ports:
      - '3000:3000'

  localstack:
    image: localstack/localstack
    privileged: true
    ports:
      - '4566-4599:4566-4599'
    environment:
      - SERVICES=lambda,sqs,iam
      - LAMBDA_EXECUTOR=docker
      - LS_LOG=debug
      - DEFAULT_REGION=eu-west-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  data-collector-api:
    build: ./
    ports:
      - '3001:3001'
    links:
      - localstack
      - provider-api-mock-service
    environment:
      - SERVER_PORT=3001
    command: npm run start:create
    depends_on:
      - localstack
      - provider-api-mock-service